import { Language } from './types';

export const PRICING = {
  bw: 2, // ₹2 per page
  color: 10, // ₹10 per page
  doubleSideDiscount: 0.5, // Subtract ₹0.5 for double side (optional)
};

export const UI_STRINGS: Record<Language, Record<string, string>> = {
  en: {
    welcome: "Welcome to Smart Print Station",
    secure: "Secure Self-Service Printing",
    touchToStart: "Touch Anywhere to Start",
    selectLanguage: "Select Language",
    selectUploadSource: "Select Upload Source",
    usb: "USB Upload",
    mobile: "Mobile QR Upload",
    typec: "Type-C Device",
    scanning: "Scanning files...",
    securityCheck: "Security check complete",
    virusDetected: "Virus detected — Upload blocked",
    preview: "Document Preview",
    printSettings: "Print Settings",
    copies: "Copies",
    printType: "Print Type",
    bw: "Black & White",
    color: "Color",
    orientation: "Orientation",
    portrait: "Portrait",
    landscape: "Landscape",
    paperSize: "Paper Size",
    printSide: "Print Side",
    single: "Single Side",
    double: "Double Side",
    totalAmount: "Total Amount",
    payNow: "Pay Now",
    printing: "Printing in Progress",
    thankYou: "Thank You for Using Smart Print Station",
    collectDocs: "Please collect your documents",
    next: "Next",
    back: "Back",
    cancel: "Cancel",
    sessionTimeout: "Session expires in {time}",
    pages: "Pages"
  },
  hi: {
    welcome: "स्मार्ट प्रिंट स्टेशन में आपका स्वागत है",
    secure: "सुरक्षित स्व-सेवा प्रिंटिंग",
    touchToStart: "शुरू करने के लिए कहीं भी स्पर्श करें",
    selectLanguage: "अपनी भाषा चुनें",
    selectUploadSource: "अपलोड स्रोत चुनें",
    usb: "USB अपलोड",
    mobile: "मोबाइल QR अपलोड",
    typec: "Type-C डिवाइस",
    scanning: "फाइलों को स्कैन किया जा रहा है...",
    securityCheck: "सुरक्षा जांच पूरी हुई",
    virusDetected: "वायरस मिला — अपलोड अवरुद्ध",
    preview: "दस्तावेज़ पूर्वावलोकन",
    printSettings: "प्रिंटिंग सेटिंग्स",
    copies: "प्रतियां",
    printType: "प्रिंट का प्रकार",
    bw: "ब्लैक एंड व्हाइट",
    color: "रंगीन",
    orientation: "अभिविन्यास",
    portrait: "पोर्ट्रेट",
    landscape: "लैंडस्केप",
    paperSize: "कागज का आकार",
    printSide: "प्रिंट साइड",
    single: "एक तरफ",
    double: "दोनों तरफ",
    totalAmount: "कुल राशि",
    payNow: "अब भुगतान करें",
    printing: "प्रिंटिंग जारी है",
    thankYou: "स्मार्ट प्रिंट स्टेशन का उपयोग करने के लिए धन्यवाद",
    collectDocs: "कृपया अपने दस्तावेज़ एकत्र करें",
    next: "आगे",
    back: "पीछे",
    cancel: "रद्द करें",
    sessionTimeout: "सत्र {time} में समाप्त हो जाएगा",
    pages: "पृष्ठ"
  },
  mr: {
    welcome: "स्मार्ट प्रिंट स्टेशनवर आपले स्वागत आहे",
    secure: "सुरक्षित स्व-सेवा प्रिंटिंग",
    touchToStart: "सुरू करण्यासाठी कुठेही स्पर्श करा",
    selectLanguage: "भाषा निवडा",
    selectUploadSource: "अपलोड स्रोत निवडा",
    usb: "USB अपलोड",
    mobile: "मोबाईल QR अपलोड",
    typec: "Type-C डिव्हाइस",
    scanning: "फाईल्स स्कॅन होत आहेत...",
    securityCheck: "सुरक्षा तपासणी पूर्ण झाली",
    virusDetected: "व्हायरस आढळला — अपलोड ब्लॉक केले",
    preview: "दस्तऐवज पूर्वावलोकन",
    printSettings: "प्रिंटिंग सेटिंग्ज",
    copies: "प्रती",
    printType: "प्रिंट प्रकार",
    bw: "ब्लॅक अँड व्हाईट",
    color: "रंगीत",
    orientation: "ओरिएंटेशन",
    portrait: "पोर्ट्रेट",
    landscape: "लँडस्केप",
    paperSize: "कागदाचा आकार",
    printSide: "प्रिंट बाजू",
    single: "एका बाजूला",
    double: "दोन्ही बाजूला",
    totalAmount: "एकूण रक्कम",
    payNow: "आत्ता पैसे द्या",
    printing: "प्रिंटिंग प्रगतीपथावर आहे",
    thankYou: "स्मार्ट प्रिंट स्टेशन वापरल्याबद्दल धन्यवाद",
    collectDocs: "कृपया आपले दस्तऐवज गोळा करा",
    next: "पुढील",
    back: "मागे",
    cancel: "रद्द करा",
    sessionTimeout: "सत्र {time} मध्ये संपेल",
    pages: "पृष्ठे"
  }
};
